### ISSUE TITLE
直接用jar包出现错误，非java开发

### ISSUE THREAD

**Issue by RXlung** [1015770492/autoRefreshCSDN#6]
PS H:\> java -jar .\autoRefreshCSDN-1.0-SNAPSHOT-jar-with-dependencies.jar "具体地址" 55
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: test/AutoReFreshCSDNDemo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)

出现这个是啥？我查了下说java版本不一致，可是javac或java命令都是1.8版本，难道说编译出来的jar里面有指定什么java版本？

**Comment by 1015770492** [comment]
用jdk15跑，代码里面用了java的新特性。
